/**
 * Direção editorial gastronômica: carvão, ouro fosco e creme; títulos Fraunces
 * com corpo Manrope; fotografia do PDF em composição assimétrica. Entradas CSS
 * discretas e progressivas; sem animações que bloqueiem leitura ou navegação.
 * Uma ação principal (cardápio), provas sociais reais e informação escaneável.
 */
import Image from 'next/image';
import Link from 'next/link';
import { ArrowRight, ChefHat, Fish, Users, Star } from 'lucide-react';
import { Header } from '../components/Header';
import { Footer } from '../components/Footer';
import { FAQ } from '../components/FAQ';
import { Button } from '../components/ui/button';
import { Badge } from '../components/ui/badge';
import { Card, CardContent } from '../components/ui/card';
import { Avatar, AvatarFallback } from '../components/ui/avatar';
const reviews=[{name:'Fernanda Souza',initials:'FS',text:'Um lugar muito agradável e o peixe e os drinks uma delícia'},{name:'Gonçalves CaçulaNet',initials:'GC',text:'Tudo muito bom, atendimento, comida, preço, ambiente e trilha sonora!'},{name:'Nelson Bruder Junior',initials:'NB',text:'Ótimo atendimento e ótima qualidade dos pratos e produtos'}];
export default function HomePage(){return <div className="new-home"><Header/><main>
<section className="editorial-hero section-shell"><div className="hero-copy"><Badge>BOTUCATU · RESTAURANTE & PETISCARIA</Badge><h1>Sabor de mar.<br/><em>Noite para<br/>ficar.</em></h1><p>Peixes, camarões e petiscos para uma mesa cheia de bons momentos. Esse é o The Fish.</p><Button asChild size="lg"><Link href="/cardapio">Ver cardápio e pedir <ArrowRight size={20}/></Link></Button><div className="hero-proof"><Star size={18} fill="currentColor"/><strong>4,5</strong><span>no Google · 207 avaliações informadas</span></div></div><div className="hero-photo"><Image src="/assets/menu/chef.png" alt="Camarão na moranga apresentado no cardápio The Fish" fill priority sizes="(max-width: 760px) 100vw, 50vw"/><div className="photo-caption"><span>DA NOSSA COZINHA</span><strong>Camarão na moranga</strong></div><span className="photo-index">01 / THE FISH</span></div><div className="hero-bottom"><span>PEIXES & FRUTOS DO MAR</span><span>FEITO PARA COMPARTILHAR</span><span>VILA NOVA BOTUCATU</span></div></section>
<section className="signature-section section-shell"><div className="section-top"><div><p className="section-kicker">A NOITE TEM SEUS FAVORITOS</p><h2>Da primeira garfada<br/><em>ao último petisco.</em></h2></div><p>Pratos do chef, porções e combinados.<br/>Encontre o que combina com a sua mesa.</p></div><div className="signature-grid"><Card className="signature-card signature-wide"><div className="signature-image"><Image src="/assets/menu/combinados.jpeg" alt="Camarões à milanesa do cardápio" fill sizes="(max-width:760px) 100vw, 60vw"/></div><CardContent><span className="section-kicker">PEIXES & CAMARÕES</span><h3>O mar é a nossa especialidade.</h3><p>Da tilápia aos camarões, escolha seus favoritos e o preparo que você prefere.</p></CardContent></Card><Card className="signature-card"><div className="signature-image"><Image src="/assets/menu/boteco.jpeg" alt="Torresmo com mandioca do cardápio Boteco" fill sizes="(max-width:760px) 100vw, 35vw"/></div><CardContent><span className="section-kicker">PORÇÕES BOTECO</span><h3>Mais uma rodada de conversa.</h3><p>Torresmo caipira, linguiça bêbada e empanados de Gouda para compartilhar.</p></CardContent></Card></div></section>
<section id="restaurante" className="story-section section-shell"><div className="story-heading"><p className="section-kicker">PRAZER, THE FISH</p><h2>Boa comida.<br/>Boa companhia.<br/><em>Bem aqui.</em></h2></div><div className="story-content"><p className="story-lead">Um restaurante e petiscaria em Botucatu para quem gosta de peixes, frutos do mar e de aproveitar a noite à mesa.</p><p>Ingredientes frescos, pratos preparados com cuidado e opções para diferentes momentos. Venha para um prato individual ou reúna os amigos para dividir as porções.</p><div className="benefit-list"><div><ChefHat/><span><strong>Cozinha com personalidade</strong>Pratos do chef e sabores do mar.</span></div><div><Users/><span><strong>Uma mesa para compartilhar</strong>Combinados e porções para escolher juntos.</span></div><div><Fish/><span><strong>Escolha do seu jeito</strong>Monte o pedido e confirme pelo WhatsApp.</span></div></div></div></section>
<section className="reviews-section section-shell"><div className="section-top"><div><p className="section-kicker">QUEM VEIO, CONTA</p><h2>Histórias que ficam<br/><em>depois da mesa.</em></h2></div><div className="review-score"><strong>4,5<span>/5</span></strong><p>Google · avaliações informadas</p></div></div><div className="review-grid">{reviews.map(r=><Card className="review-card" key={r.name}><CardContent><span className="quote-mark" aria-hidden="true">“</span><blockquote>{r.text}</blockquote><div className="review-person"><Avatar><AvatarFallback>{r.initials}</AvatarFallback></Avatar><div><strong>{r.name}</strong><span>Avaliação no Google</span></div></div></CardContent></Card>)}</div></section>
<FAQ/>
<section className="final-invitation"><div className="section-shell"><p className="section-kicker">A SUA PRÓXIMA NOITE COMEÇA AQUI</p><h2>Escolha o sabor.<br/><em>A companhia é sua.</em></h2><p>Monte seu pedido e fale com nossa equipe pelo WhatsApp.</p><Button asChild size="lg"><Link href="/cardapio">Montar meu pedido <ArrowRight size={20}/></Link></Button></div></section>
</main><Footer/></div>;}
